name: LinDB CI
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2-beta
        with:
          go-version: 1.14

      - name: Display golang info
        shell: bash
        run: |
          echo $(go version) at $(which go)
          echo go version: $(go version)
          echo cache: $(ls $RUNNER_TOOL_CACHE/go)
          echo go env: $(go env GOPATH)

      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Test on ubuntu
        shell: bash
        run: make mock-check-test
        if: matrix.os == 'ubuntu-latest'

      - name: Test on windows
        shell: bash
        run: make mock-test
        if: matrix.os == 'windows-latest'

      - name: codecov
        shell: bash
        run: bash <(curl -s https://codecov.io/bash) -t 571f35bb-4929-4ac5-88cd-8d2c21302b40

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2-beta
        with:
          go-version: 1.14

      - name: Display golang info
        shell: bash
        run: |
          echo $(go version) at $(which go)
          echo go version: $(go version)
          echo cache: $(ls $RUNNER_TOOL_CACHE/go)
          echo go env: $(go env GOPATH)

      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Build
        shell: bash
        run: |
          make build
